import numpy as np
import numpy.typing as npt

def performance_profiler() -> int: ...
def _permanent_single_f32(matrix: npt.NDArray[np.float32]) -> np.float32: ...
def _permanent_single_f64(matrix: npt.NDArray[np.float64]) -> np.float64: ...
def _permanent_single_cf32(
    matrix: npt.NDArray[np.complex64],
) -> np.complex64: ...
def _permanent_single_cf64(
    matrix: npt.NDArray[np.complex128],
) -> np.complex128: ...
def _permanent_multi_f32(matrix: npt.NDArray[np.float32]) -> np.float32: ...
def _permanent_multi_f64(matrix: npt.NDArray[np.float64]) -> np.float64: ...
def _permanent_multi_cf32(
    matrix: npt.NDArray[np.complex64],
) -> np.complex64: ...
def _permanent_multi_cf64(
    matrix: npt.NDArray[np.complex128],
) -> np.complex128: ...
