name: Code testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  python-test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        include:
          - python-version: 3.13
            os: windows-latest
          - python-version: 3.13
            os: macos-latest

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
            uv venv
            uv pip install -r requirements.txt

      - name: Build with maturin
        run: uv run maturin develop --release

      - name: Test with pytest
        run: uv run pytest

  rust-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run cargo tests
        run: cargo test